apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  ports:
  - port: 3306
    name: mysql
  clusterIP: None
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql # has to match .spec.template.metadata.labels
  serviceName: "mysql"
  replicas: 1 # by default is 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: mysql # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc      
      containers:
      - name: mysql
        image: mysql:8
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: dados
              key: DB_DATABASE
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: senhas
              key: DB_PASSWORD

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-hostpath-sc
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: mysql-dump
spec:
  schedule: "0 3 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mysql-dump
            image: leonardosartorello/mysqldump:v4
            imagePullPolicy: IfNotPresent
            env:
            - name: MYSQL_ENV_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: dados
                  key: DB_HOST
            - name: MYSQL_ENV_DB_USER
              valueFrom:
                secretKeyRef:
                  name: senhas
                  key: DB_USER
            - name: MYSQL_ENV_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: senhas
                  key: DB_PASSWORD
            volumeMounts:
            - name: mysqldump
              mountPath: /mysqldump              
          restartPolicy: OnFailure
          volumes:
          - name: mysqldump
            hostPath:
              path: /tmp/mysqldump